push/push.go
If you do `mp plan -m "title\nbody"`, this now results in a PR title of `title` and a PR body of `body`. Previously, it would join the multi-line string into a giant single line PR title. Not good.
=> Split multiline commit message into PR title and body

Gopkg.lock, Gopkg.toml, cmd/status.go, plan/plan.go
Status now
(1) prints errors in red b2d4bb2
This helps make errors easier to pick out among all the status output.
(2) shows # of files changed 25357c4
This is useful in case one repo has a strange number of lines changed. In the long-run, we may want to automatically surface "surprising" diffs (e.g. everything has 1 file change, but some repo has != 1 files changed).
(3) Also includes an unrelated bugfix to copy all files, including symlinks 85c7479 This was an error that would have been easier to catch if we had (2)
=> Improve mp status output

cmd/merge.go, cmd/root.go, merge/merge.go
These UX improvements help make the merge command more responsive by exiting early when possible (d02cbd7) and preventing hammering the CI system via a configurable `--throttle <time>` flag (f384758).
When running my most recent Microplane change, I used `--throttle 60s` to ensure I wasn't merging too quickly and hammering CI during working hours.
=> Merge ux improvements

Gopkg.lock, cmd/merge.go, cmd/root.go, cmd/status.go, merge/merge.go
Previously, `merge` checked if a PR was mergeable (no rebase needed) and
also inspected its github status (e.g. "are unit tests passing via CI?")
Now, `merge `also inspects whether 1 or more reviewers has accepted
the PR. You can override this check by passing
```
mp merge --ignore-review-approval
```
=> Before merging, require PR approval (allow override)

cmd/merge.go, cmd/push.go, cmd/root.go, push/push.go
this can be used to prevent pushing commits too aggressively and overwhelming CI
we already support throttling for `mp merge`, so I copied that approach here
=> allow throttling push

cmd/merge.go, cmd/root.go, merge/merge.go
Without this flag it is impossible to automatically merge PRs for repos without some kind of CI.
=> Add flag to ignore build status when merging

cmd/init.go, cmd/root.go, initialize/initialize.go
Previously, we required the user to do a GitHub (or GitLab) search to
generate the initial list of repos.
What if you... already know... the repos you want to target? :)
The previous UX was actually more painful.
This should make it easier to just declare your repo list and move on.
=> allow init from file

cmd/root.go
this lessens the chance of hammering your CI system without realizing
what you're doing
=> 30s default throttle for merge/push

cmd/init.go, cmd/root.go, docs/mp_init.md, initialize/initialize.go
[Link to JIRA](https://clever.atlassian.net/browse/IL-2090)
Currently `mp init` command searches code, not repositories. In this PR, I change the code from searching code -> repos.
I don't see an easy way to test the change except from merging it and trying it with 1 script.
=> search repos not code

push/push.go
This fixes the issue with `--body-file` as was brought up in #57, but with the additional request from maintainer to update the body to be a combination of the commit message + body-file content if both are given.
Closes #57 
- I wasn't able to test or build locally unfortunately. `make test` returned the following for me:
```
FORMATTING _/Users/gowiem/Workspace/Cloned/microplane...
stat /Users/gowiem/Workspace/go/src/_/Users/gowiem/Workspace/Cloned/microplane/*.go: no such file or directory
error running command: exit status 2
make: *** [_/Users/gowiem/Workspace/Cloned/microplane] Error 1
```
=> Fixes --body-file flag usage

.circleci/config.yml, Makefile
Bump to go 1.15
relates to https://github.com/Homebrew/homebrew-core/pull/59749
=> chore(deps): upgrade to go1.15

.circleci/config.yml
fixup for #61 
Looks like Debian Stretch was superseded by Debian Buster on 2019-07-06
https://wiki.debian.org/DebianStretch
https://hub.docker.com/layers/circleci/golang/1.15-buster/images/sha256-2930f56c9f5973254c37e329d476e639a8ac1d4672eea042716b1182dbe1485f?context=explore
=> golang:1.15-stretch dne. use -buster instead

Gopkg.lock, cmd/push.go, cmd/root.go, initialize/initialize.go, push/push.go
This adds the ability to specify labels on opened PRs.
The current implementation will only check if there are no labels and if
there are not, add them. Further enhancements should loop through all
the labels and check the specified labels match the existing ones
Note: this also updates the version of `github.com/google/go-github` which returns the labels from the pr call
=> add support for labels

cmd/helpers.go, cmd/plan.go, cmd/root.go, docs/mp_plan.md
- Parallelism limit added for `plan` command. Useful if your script for plan is not working in parallel (just set parallelism limit to 1)
=> Parallelism limit added for plan command

README.md, cmd/clone.go, initialize/initialize.go, lib/provider.go, lib/repo.go
n/a
Allows microplane to work with Github enterprise.
Caveat noted in README: _Self-hosted Github setup with different URLs for the main API and uploads API are not yet supported. If this is a blocker for you, please file an issue or make a PR._
=> Support Github enterprise

cmd/root.go, cmd/version.go
Adds a `version` subcommand so users can check the current version. 
And this is very much baby's first Golang contribution, so let me know if there's anything I should fix, or any wording tweaks :+1: 
Confirmed that it works:
```
> mp version
microplane 0.0.30
```
And that `--help` gives the right description:
```
> mp version --help
Print the current microplane version
Usage:
mp version [flags]
Flags:
-h, --help   help for version
Global Flags:
-r, --repo string   single repo to operate on
```
=> Add version subcommand

CHANGELOG.md, cmd/plan.go, cmd/root.go, plan/plan.go
_Give a high level description of your changes._
I've found I often like seeing the diffs of all changes made in all repos, but currently `plan` only shows the diff if there's just one repo (which is understandable, to not spew page after page of diffs by default).
This adds a `--diff` flag to optionally show all diffs, separated by repo with a `diffing: org/repo` message before each diff.
Now that there's a flag to show diffs, I removed the previous default action of showing a diff if there's just one repo being worked with. I thought the user might find it unexpected to see a diff without explicitly setting the diff flag (let me know if I should keep that in there though).
_Describe testing you did to ensure your changes work and that existing functionality was not broken by the …
=> Add a `--diff` flag to `mp plan`

CHANGELOG.md, cmd/merge.go, cmd/root.go, merge/merge.go
As per #103, this adds the option to set which merge method to use (e.g. squash or rebase). 
fixes #103
=> feat: Add merge-method option

push/push.go, push/pushGitlab.go
n/a
**feat: use the default branch as the Gitlab PR target**
Previously, the target branch for the PR when using Gitlab was hardcoded
to "master". Now the repositories default branch will be used.
**refactor: the Gitlab PR body to be consistent with Github**
Now both Gitlab and Github have the same logic for creating the PR title
and body. It will use the first line of the commit as the title then
concatenate the commit body and the content of the PRBody file that is
passed in as a parameter
Tested locally and have been using microplane with this patch for a while.
=> Updates to Gitlab PRs

README.md
README.md
N/A
fix provider url flag to have hyphen instead of underscores
Ran the command `mp init --provider-url=...`  on the CLI
=> chore(README): fix provider url flag to have hyphen instead of underscores

.circleci/config.yml, Makefile, go.mod
Update to use the latest go release, go1.17
_Describe testing you did to ensure your changes work and that existing functionality was not broken by the changes._
=> build: use go1.17

cmd/status.go, go.mod
none
As of Aug 2019, the fork had already been merged into the upstream repo https://github.com/waigani/diffparser So we don't need it anymore!
None
=> Remove outdated fork of diffparser lib

cmd/push.go
n/a 
closes #129
The `labels` flag was difficult to use. This improves the docs.
Build locally and sanity checked help text
```
$ ./bin/mp push --help
Push planned changes
Usage:
mp push [flags]
Flags:
-a, --assignee string                             Github user to assign the PR to
-b, --body-file string                            body of PR
-d, --draft                                       push a draft pull request (only supported for github)
-h, --help                                        help for push
-l, --labels -l 'first label' -l 'second label'   labels to attach to PR. for example: -l 'first label' -l 'second label'
-t, --throttle string                             Throttle number of pushes, e.g. '30s' means 1 push per 30 seconds (default "30s")
Global Flags:
-r, --repo string …
```
=> improve push help docs for labels.

cmd/plan.go, go.mod, go.sum, plan/plan.go
There are cases where we would like to push an empty commit and trigger a build, e.g. if the build process pulls in the latest version of something.
This PR adds a flag to `plan` that allows for this.
=> allow empty commits

plan/plan.go
Instead of just returning the command output, the `Plan` function will:
- return the go error if the planned command cannot be executed at all
- prefix the output with the error message containing the exit code if the command fails
```
~/D/e/20220513-microplane-sandbox ❯❯❯ microplane plan -b test -m test -- foo
2022/05/13 12:44:12 planning 1 repos with parallelism limit [10]
2022/05/13 12:44:12 planning: gdetrez/sandbox
2022/05/13 12:44:12 1 errors:
gdetrez/sandbox error: exec: "foo": executable file not found in $PATH
❯❯❯ microplane plan -b test -m test -- sh -c 'echo Kaboom!; exit 42'
2022/05/13 12:44:06 planning 1 repos with parallelism limit [10]
2022/05/13 12:44:06 planning: gdetrez/sandbox
2022/05/13 12:44:06 1 errors:
gdetrez/sandbox error: [exit status 42] Kaboom!
```
=> Improve plan error output

plan/plan.go
This param adds extra chars in the git diff, and because of this, the parser doesn't know how to parser it.
NA
This param adds extra chars in the git diff, and because of this, the parser doesn't know how to parser it.
Before the change: Init, Clone, Plan, Status, status shows 0 file changes.
After the change: Init, Clone, Plan, Status, status shows 174 file changes.
=> Remove --color param in "git diff" for the plane command
